### ISSUE TITLE
Firebird not showing up in Add Database

### ISSUE THREAD

**Issue by alexfrench** [evosec/metabase-firebird-driver#5]
Hi

Thanks for developing the plugin.  I added firebird.metabase-driver.jar to the plugins folder and restarted the container.

This appears in the log:
INFO plugins.classloader :: Added URL file:/plugins/firebird.metabase-driver.jar to classpath

There is no further reference to the driver in the log. When I go to Add Database, Firebird is not listed.

Did I miss a step? If not, what do you suggest to debug this?

Thanks

**Comment by Nikos410** [comment]
Hey there,

which versions are you running? You need at least version 0.32.x of Metabase, earlier versions did not support including database drivers as plugins. 

If you are already doing that, please try using [version 1.1.0](https://github.com/evosec/metabase-firebird-driver/releases/tag/v1.1) of this driver. We just released the latest version yesterday, maybe there is a bug that we did not catch when testing.

**Comment by alexfrench** [comment]
Hi Nikos

We are running metabase v0.35.0-rc1 (upgraded from 0.33 via 0.34 when we found there was a problem with the plugin). 

We were trying to run V1.2.0 of the plugin. Again, I had tried an earlier version.

I tried V1.1 just now but it made no difference. It is still not loading.

Thanks.
Alex

**Comment by alexfrench** [comment]
Hi Nikos

Did you have any further suggestions for this? Thanks.

**Comment by Nikos410** [comment]
Hi Alex,

sorry for not responding earlier.

Honestly, I have no idea why this is happening, I've never seen that issue before - in fact I have never even seen the log message `INFO plugins.classloader :: Added URL file:/plugins/firebird.metabase-driver.jar to classpath` before either. But that is probably because we are running Metabase from a .jar file directly and you are running it in a container, it probably has nothing to do with this issue.

Most other drivers that are bundled with Metabase (for example SQLServer) are extracted to the plugins directory and then loaded as seperate .jar files on startup as well, do these drivers work?

```
kevdev39:/srv/metabase-test # ll plugins/
total 109164
-rw-r--r-- 1 root root   542445 Feb 25 12:36 bigquery.metabase-driver.jar
-rw-r--r-- 1 root root   465484 Feb 25 12:36 druid.metabase-driver.jar
-rw-r--r-- 1 root root  1639115 Mar 16 11:20 firebird.metabase-driver.jar
-rw-r--r-- 1 root root  1065416 Feb 25 12:36 google.metabase-driver.jar
-rw-r--r-- 1 root root   720690 Feb 25 12:36 googleanalytics.metabase-driver.jar
-rw-r--r-- 1 root root  4594054 Feb 25 12:36 mongo.metabase-driver.jar
-rw-r--r-- 1 root root    69265 Feb 25 12:36 oracle.metabase-driver.jar
-rw-r--r-- 1 root root   140904 Feb 25 12:36 presto.metabase-driver.jar
-rw-r--r-- 1 root root  2381206 Feb 25 12:36 redshift.metabase-driver.jar
-rw-r--r-- 1 root root 28938832 Feb 25 12:36 snowflake.metabase-driver.jar
-rw-r--r-- 1 root root 62798758 Feb 25 12:36 sparksql.metabase-driver.jar
-rw-r--r-- 1 root root  7115159 Feb 25 12:36 sqlite.metabase-driver.jar
-rw-r--r-- 1 root root  1230898 Feb 25 12:36 sqlserver.metabase-driver.jar
-rw-r--r-- 1 root root    50756 Feb 25 12:36 vertica.metabase-driver.jar
```

If these drivers don't appear in the `plugins` directory or are not loaded properly either, this might be an issue with Metabase itself or your setup. 

If the bundled drivers work fine, you could try installing another third party driver, like the [clickhouse driver](https://github.com/enqueue/metabase-clickhouse-driver), to see if this issue occurs with other third party plugins as well.

Finally, you could try [decreasing the log level to DEBUG](https://www.metabase.com/docs/latest/operations-guide/log-configuration.html) to see if that reveals any more information. [This](https://gist.github.com/Nikos410/5b9d86a4202359d8afb19dba5c89647f) is the log config I usually use for debugging, it makes Metabase log EVERYTHING into a file called `metabase.log`.

**Comment by dacort** [comment]
Hi all, Damon from Metabase here. 👋 

Drivers are currently fairly specific to the major version they've been compiled against, so if `v1.2.0` was built against Metabase 0.34.x, you should use 034.x with it. ~~That's likely what you're seeing @alexfrench.~~ That said, I just gave this a shot with `0.35.0-rc1` and `FirebirdSQL` showed up in "Add Database" for me. You should see lines like this after the log line you posted:
```
03-20 08:52:39 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.firebird...
03-20 08:52:39 INFO driver.impl :: Registered driver :firebird (parents: [:sql-jdbc]) 🚚
03-20 08:52:39 DEBUG plugins.jdbc-proxy :: Registering JDBC proxy driver for class org.firebirdsql.jdbc.FBDriver...
Load lazy loading driver :firebird took 78.6 ms
```

@Nikos410 As a heads up, there are some potential breaking changes with drivers in 0.35.x ([wiki](https://github.com/metabase/metabase/wiki/What's-new-in-0.35.0-for-Metabase-driver-authors)), so be sure to take a look at that.

**Comment by Nikos410** [comment]
Thanks @dacort! Created #7.

I guess this is not the last time there will be some changes to the driver interface, is there a place where these are announced so third-party driver developers will not miss them?

**Comment by dacort** [comment]
Yep, there are a couple places:
- Discourse - there's a new [driver development](https://discourse.metabase.com/c/driver-development) category. 
- Email - If you prefer a low-volume email list dedicated to the announcements, you can find the sign-up link on the [driver development docs](https://www.metabase.com/docs/latest/developers-guide-drivers.html#driver-development-announcements).

Also, thanks for your work on the driver. 🙏  As an FYI, I've added it to our list of [community drivers](https://www.metabase.com/docs/latest/developers-guide-drivers.html).
